import pytest
import csv
from pathlib import Path
from types import SimpleNamespace
from dbcheck.config import AssignmentConfig
from dbcheck.snapshot.normalizer import NameNormalizer
from dbcheck.structure.constraint_checker import match_constraints
from dbcheck.utils.summary import compile_summary
from dbcheck.utils.scoring import get_answer_atomic_items, score_submission

@pytest.fixture
def fk_config_data():
    return {
        "assignment": {
            "name": "FK Relationship Test",
            "protected_answer_db": "00000001"
        },
        "schema": {
            "matching_threshold": 0.8,
            "table_accept_threshold": 0.9,
            "table_ambiguous_threshold": 0.75,
            "column_accept_threshold": 0.88,
            "column_ambiguous_threshold": 0.75,
            "aliases": {
                "tables": {
                    "HangHoa": ["HangTonKho"],
                    "ChiTietMuaHang": ["CT_MuaHang"]
                },
                "columns": {
                    "global": {},
                    "by_table": {
                        "ChiTietMuaHang": {
                            "MaHangHoa": ["MaHang"]
                        },
                        "HangHoa": {
                            "MaHangHoa": ["MaHTK"]
                        }
                    }
                }
            },
            "abbreviations": {},
            "key_grading": {
                "mode": "adequacy",
                "allow_surrogate_keys": True,
                "allow_natural_keys": True,
                "require_business_key_uniqueness": True,
                "surrogate_key_patterns": ["id", "{table}id", "{table}_id"]
            }
        },
        "views": {
            "mode": "answer_snapshot",
            "expected": []
        }
    }

def test_fk_name_differs_but_relationship_matches(fk_config_data):
    config = AssignmentConfig(fk_config_data)
    
    # Expected relationship (Answer)
    ans_fks = [{
        "fk_name": "FK_ChiTietMuaHang_HangHoa",
        "parent_table_canonical": "ChiTietMuaHang",
        "parent_column_canonical": "MaHangHoa",
        "referenced_table_canonical": "HangHoa",
        "referenced_column_canonical": "MaHangHoa",
        "delete_rule": "NO_ACTION",
        "update_rule": "NO_ACTION"
    }]
    
    # Student FK with different name and physical names that map canonically
    stud_fks = [{
        "fk_name": "FK_random_123",
        "parent_table": "CT_MuaHang",
        "parent_column": "MaHang",
        "referenced_table": "HangTonKho",
        "referenced_column": "MaHTK",
        "parent_table_canonical": "ChiTietMuaHang",
        "parent_column_canonical": "MaHangHoa",
        "referenced_table_canonical": "HangHoa",
        "referenced_column_canonical": "MaHangHoa",
        "delete_rule": "NO_ACTION",
        "update_rule": "NO_ACTION"
    }]
    
    stud_cols = [
        {"table_name": "CT_MuaHang", "column_name": "MaHang", "column_name_canonical": "MaHangHoa", "is_nullable": 0, "is_identity": 0},
        {"table_name": "HangTonKho", "column_name": "MaHTK", "column_name_canonical": "MaHangHoa", "is_nullable": 0, "is_identity": 0}
    ]
    ans_cols = [
        {"table_name_canonical": "ChiTietMuaHang", "column_name_canonical": "MaHangHoa", "column_name": "MaHangHoa", "is_identity": 0},
        {"table_name_canonical": "HangHoa", "column_name_canonical": "MaHangHoa", "column_name": "MaHangHoa", "is_identity": 0}
    ]
    
    _, _, fk_report, counts = match_constraints(
        [], [], ans_fks, stud_fks,
        {"ChiTietMuaHang": "CT_MuaHang", "HangHoa": "HangTonKho"},
        config, [], ans_cols, stud_cols, []
    )
    
    assert len(fk_report) == 1
    assert fk_report[0]["fk_status"] == "FK_RELATIONSHIP_MATCH_ALIAS_EQUIVALENT"
    assert counts["fk_alias_equivalent_count"] == 1

def test_fk_autogenerated_name_passes(fk_config_data):
    config = AssignmentConfig(fk_config_data)
    
    ans_fks = [{
        "fk_name": "FK_ChiTietMuaHang_HangHoa",
        "parent_table_canonical": "ChiTietMuaHang",
        "parent_column_canonical": "MaHangHoa",
        "referenced_table_canonical": "HangHoa",
        "referenced_column_canonical": "MaHangHoa",
        "delete_rule": "NO_ACTION",
        "update_rule": "NO_ACTION"
    }]
    
    # Auto-generated SQL Server constraint name, but physical and canonical columns match
    stud_fks = [{
        "fk_name": "FK__CT_MuaHan__MaHan__239E209F",
        "parent_table": "CT_MuaHang",
        "parent_column": "MaHang",
        "referenced_table": "HangTonKho",
        "referenced_column": "MaHTK",
        "parent_table_canonical": "ChiTietMuaHang",
        "parent_column_canonical": "MaHangHoa",
        "referenced_table_canonical": "HangHoa",
        "referenced_column_canonical": "MaHangHoa",
        "delete_rule": "NO_ACTION",
        "update_rule": "NO_ACTION"
    }]
    
    stud_cols = [
        {"table_name": "CT_MuaHang", "column_name": "MaHang", "column_name_canonical": "MaHangHoa", "is_nullable": 0, "is_identity": 0},
        {"table_name": "HangTonKho", "column_name": "MaHTK", "column_name_canonical": "MaHangHoa", "is_nullable": 0, "is_identity": 0}
    ]
    ans_cols = [
        {"table_name_canonical": "ChiTietMuaHang", "column_name_canonical": "MaHangHoa", "column_name": "MaHangHoa", "is_identity": 0},
        {"table_name_canonical": "HangHoa", "column_name_canonical": "MaHangHoa", "column_name": "MaHangHoa", "is_identity": 0}
    ]
    
    _, _, fk_report, counts = match_constraints(
        [], [], ans_fks, stud_fks,
        {"ChiTietMuaHang": "CT_MuaHang", "HangHoa": "HangTonKho"},
        config, [], ans_cols, stud_cols, []
    )
    
    assert len(fk_report) == 1
    assert fk_report[0]["fk_status"] == "FK_RELATIONSHIP_MATCH_ALIAS_EQUIVALENT"

def test_fk_implied_relationship_emitted(fk_config_data):
    config = AssignmentConfig(fk_config_data)
    
    ans_fks = [{
        "fk_name": "FK_ChiTietMuaHang_HangHoa",
        "parent_table_canonical": "ChiTietMuaHang",
        "parent_column_canonical": "MaHangHoa",
        "referenced_table_canonical": "HangHoa",
        "referenced_column_canonical": "MaHangHoa",
        "delete_rule": "NO_ACTION",
        "update_rule": "NO_ACTION"
    }]
    
    # No declared student FK, but columns exist
    stud_cols = [
        {"table_name": "CT_MuaHang", "column_name": "MaHang", "column_name_canonical": "MaHangHoa", "is_nullable": 0, "is_identity": 0},
        {"table_name": "HangTonKho", "column_name": "MaHTK", "column_name_canonical": "MaHangHoa", "is_nullable": 0, "is_identity": 0}
    ]
    ans_cols = [
        {"table_name_canonical": "ChiTietMuaHang", "column_name_canonical": "MaHangHoa", "column_name": "MaHangHoa", "is_identity": 0},
        {"table_name_canonical": "HangHoa", "column_name_canonical": "MaHangHoa", "column_name": "MaHangHoa", "is_identity": 0}
    ]
    
    _, _, fk_report, counts = match_constraints(
        [], [], ans_fks, [],
        {"ChiTietMuaHang": "CT_MuaHang", "HangHoa": "HangTonKho"},
        config, [], ans_cols, stud_cols, []
    )
    
    assert len(fk_report) == 1
    assert fk_report[0]["fk_status"] == "FK_RELATIONSHIP_IMPLIED_REVIEW_REQUIRED"
    assert counts["fk_review_required_count"] == 1

def test_fk_wrong_parent(fk_config_data):
    config = AssignmentConfig(fk_config_data)
    
    ans_fks = [{
        "fk_name": "FK_ChiTietMuaHang_HangHoa",
        "parent_table_canonical": "ChiTietMuaHang",
        "parent_column_canonical": "MaHangHoa",
        "referenced_table_canonical": "HangHoa",
        "referenced_column_canonical": "MaHangHoa",
        "delete_rule": "NO_ACTION",
        "update_rule": "NO_ACTION"
    }]
    
    # Student points child to wrong parent table
    stud_fks = [{
        "fk_name": "FK_random",
        "parent_table": "CT_MuaHang",
        "parent_column": "MaHang",
        "referenced_table": "NhaCungCap",
        "referenced_column": "MaNCC",
        "parent_table_canonical": "ChiTietMuaHang",
        "parent_column_canonical": "MaHangHoa",
        "referenced_table_canonical": "NhaCungCap",
        "referenced_column_canonical": "MaNhaCungCap",
        "delete_rule": "NO_ACTION",
        "update_rule": "NO_ACTION"
    }]
    
    stud_cols = [
        {"table_name": "CT_MuaHang", "column_name": "MaHang", "column_name_canonical": "MaHangHoa", "is_nullable": 0, "is_identity": 0},
        {"table_name": "NhaCungCap", "column_name": "MaNCC", "column_name_canonical": "MaNhaCungCap", "is_nullable": 0, "is_identity": 0}
    ]
    ans_cols = [
        {"table_name_canonical": "ChiTietMuaHang", "column_name_canonical": "MaHangHoa", "column_name": "MaHangHoa", "is_identity": 0},
        {"table_name_canonical": "HangHoa", "column_name_canonical": "MaHangHoa", "column_name": "MaHangHoa", "is_identity": 0}
    ]
    
    _, _, fk_report, counts = match_constraints(
        [], [], ans_fks, stud_fks,
        {"ChiTietMuaHang": "CT_MuaHang", "HangHoa": "HangTonKho"},
        config, [], ans_cols, stud_cols, []
    )
    
    assert len(fk_report) == 1
    assert fk_report[0]["fk_status"] == "FK_RELATIONSHIP_WRONG_PARENT"
    assert counts["fk_wrong_target_count"] == 1

def test_fk_wrong_child_columns(fk_config_data):
    config = AssignmentConfig(fk_config_data)
    
    ans_fks = [{
        "fk_name": "FK_ChiTietMuaHang_HangHoa",
        "parent_table_canonical": "ChiTietMuaHang",
        "parent_column_canonical": "MaHangHoa",
        "referenced_table_canonical": "HangHoa",
        "referenced_column_canonical": "MaHangHoa",
        "delete_rule": "NO_ACTION",
        "update_rule": "NO_ACTION"
    }]
    
    # Child columns mismatch (e.g. references via SoLuong instead of MaHangHoa)
    stud_fks = [{
        "fk_name": "FK_random",
        "parent_table": "CT_MuaHang",
        "parent_column": "SoLuong",
        "referenced_table": "HangTonKho",
        "referenced_column": "MaHTK",
        "parent_table_canonical": "ChiTietMuaHang",
        "parent_column_canonical": "SoLuong",
        "referenced_table_canonical": "HangHoa",
        "referenced_column_canonical": "MaHangHoa",
        "delete_rule": "NO_ACTION",
        "update_rule": "NO_ACTION"
    }]
    
    stud_cols = [
        {"table_name": "CT_MuaHang", "column_name": "SoLuong", "column_name_canonical": "SoLuong", "is_nullable": 0, "is_identity": 0},
        {"table_name": "HangTonKho", "column_name": "MaHTK", "column_name_canonical": "MaHangHoa", "is_nullable": 0, "is_identity": 0}
    ]
    ans_cols = [
        {"table_name_canonical": "ChiTietMuaHang", "column_name_canonical": "MaHangHoa", "column_name": "MaHangHoa", "is_identity": 0},
        {"table_name_canonical": "HangHoa", "column_name_canonical": "MaHangHoa", "column_name": "MaHangHoa", "is_identity": 0}
    ]
    
    _, _, fk_report, counts = match_constraints(
        [], [], ans_fks, stud_fks,
        {"ChiTietMuaHang": "CT_MuaHang", "HangHoa": "HangTonKho"},
        config, [], ans_cols, stud_cols, []
    )
    
    assert len(fk_report) == 1
    assert fk_report[0]["fk_status"] == "FK_RELATIONSHIP_WRONG_CHILD_COLUMNS"
    assert counts["fk_wrong_target_count"] == 1

def test_scoring_denominator_does_not_emit_no_items(tmp_path, fk_config_data):
    config = AssignmentConfig(fk_config_data)
    run_dir = tmp_path
    
    # Create mock answer snapshot dir but NO foreign_keys.csv
    ans_snap = run_dir / "answer_snapshot"
    ans_snap.mkdir()
    (ans_snap / "tables.csv").write_text("table_name\nHangHoa\nChiTietMuaHang\n")
    
    # Write a test student reports dir with fk_relationship_report.csv
    reports_dir = run_dir / "submissions" / "student_1" / "reports"
    reports_dir.mkdir(parents=True)
    
    fk_report_file = reports_dir / "fk_relationship_report.csv"
    with open(fk_report_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "submission_id", "answer_fk_name", "student_fk_name",
            "answer_child_table", "answer_parent_table",
            "answer_child_columns", "answer_parent_columns",
            "answer_relationship_signature", "fk_status"
        ])
        writer.writeheader()
        writer.writerow({
            "submission_id": "student_1",
            "answer_fk_name": "FK_Detail_Parent",
            "student_fk_name": "FK_1",
            "answer_child_table": "ChiTietMuaHang",
            "answer_parent_table": "HangHoa",
            "answer_child_columns": "MaHangHoa",
            "answer_parent_columns": "MaHangHoa",
            "answer_relationship_signature": "ChiTietMuaHang|HangHoa|MaHangHoa|MaHangHoa",
            "fk_status": "FK_RELATIONSHIP_MATCH"
        })
        
    items = get_answer_atomic_items(run_dir, config)
    assert len(items["foreign_keys"]) == 1
    assert items["foreign_keys"][0] == "ChiTietMuaHang|HangHoa|MaHangHoa|MaHangHoa"

def test_summary_fk_counts_match_report_statuses(tmp_path):
    run_dir = tmp_path
    manifest_path = run_dir / "manifest.csv"
    with open(manifest_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["submission_id", "status"])
        writer.writeheader()
        writer.writerow({"submission_id": "student_1", "status": "OK"})
        
    reports_dir = run_dir / "submissions" / "student_1" / "reports"
    reports_dir.mkdir(parents=True)
    
    # 3 missing rows
    fk_report_file = reports_dir / "fk_relationship_report.csv"
    with open(fk_report_file, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=[
            "submission_id", "answer_relationship_signature", "fk_status"
        ])
        writer.writeheader()
        writer.writerow({"submission_id": "student_1", "answer_relationship_signature": "T1|T2|C1|C2", "fk_status": "FK_RELATIONSHIP_MISSING"})
        writer.writerow({"submission_id": "student_1", "answer_relationship_signature": "T3|T4|C3|C4", "fk_status": "FK_RELATIONSHIP_MISSING"})
        writer.writerow({"submission_id": "student_1", "answer_relationship_signature": "T5|T6|C5|C6", "fk_status": "FK_RELATIONSHIP_MISSING"})
        
    summary_path = compile_summary(run_dir)
    assert summary_path.exists()
    
    with open(summary_path, "r", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
        
    assert len(rows) == 1
    assert int(rows[0]["fk_missing_count"]) == 3
    assert int(rows[0]["fk_expected_count"]) == 3
